### PR TITLE
Debugging of Collada Loader, specifically texture handling.

### PR DESCRIPTION
**Pull request by BengtGustafsson**
Parse the surface and sampler elements required to get from a texture in a phong or lamberth effect to an image. Previous implementation relied on some user-selectable identifiers being the same in texture and image, which is absolutely not guaranteed.

Allow <image> clauses to be picked up from more places than the <library_images> that was implemented, including directly under <effect> and inside <profile_COMMON>.

Speedup of image loading by going through the list of unique materials in the mmeber variable Materials instead of each instance of the use of those materials. So no each image file is read only once as was probably intended from the onset.

### CODE REVIEW

**Comment by stancampbell3** [comment]
Bengt, who is managing this now?  I have done fixes I'd like to make.

**Comment by BengtGustafsson** [comment]
I don't know actually, but I Crista (aka Diva) pushed my changes back then. Maybe not all the way to the libopenmetaverse trunk though, as it seems.

**Comment by BengtGustafsson** [comment]
She can sometimes be reached at crista@encitra.com or skype chat at cristalopes

**Comment by BengtGustafsson** [comment]
BTW: What are those fixes? I was just discussing maybe to implement LOD uploads. What's your target?

**Comment by stancampbell3** [comment]
I was looking at fixing some issues with the wearables surrounding multiple
alpha textures or more than one attachment at a point.  Nothing finished
yet because I was hoping it was already done in Radegast.  Maybe a backport
of changes there?

**Comment by dahliaT** [comment]
I'm not aware of anyone managing libopenmetaverse bur a few of us have
commit access so if you make changes and post them to this list someone can
hopefully pull them in a reasonable period of time. It would also help if
some users tested them and gave feedback to the list.

**Comment by stancampbell3** [comment]
Thks and sorry for the comment spam

**Comment by dahliaT** [comment]
Merged. Sorry for the delay, I forgot this was sitting here.

**Pull request merged**
